"""Turn structure pairs into categorized findings and a Markdown report."""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass

from .structure import Structure

# Construct -> the requirement family a difference in it speaks to.
CONSTRUCT_FAMILY = {
    "tables": "TABLES",
    "table_cells": "TABLES",
    "html_comments": "TABLES",
    "images": "DIAGRAMS",
    "headings": "FORMATTING",
    "paragraphs": "FORMATTING",
    "lists": "FORMATTING",
    "list_items": "FORMATTING",
    "blockquotes": "FORMATTING",
    "code_blocks": "FORMATTING",
    "strong": "FORMATTING",
    "emphasis": "FORMATTING",
}


@dataclass
class Finding:
    article: str
    construct: str
    family: str
    pipeline: int
    published: int

    @property
    def delta(self) -> int:
        return self.published - self.pipeline

    @property
    def headline(self) -> str:
        if self.pipeline and not self.published:
            return "vanished in publication"
        if self.published and not self.pipeline:
            return "appeared only in publication (hand-added)"
        return "count changed"


def compare(article: str, pipeline: Structure, published: Structure) -> list[Finding]:
    """Return one Finding per construct whose count differs."""
    findings: list[Finding] = []
    pipeline_counts = pipeline.counts()
    published_counts = published.counts()

    for construct, pipeline_value in pipeline_counts.items():
        published_value = published_counts[construct]
        if pipeline_value != published_value:
            findings.append(
                Finding(
                    article=article,
                    construct=construct,
                    family=CONSTRUCT_FAMILY.get(construct, "OTHER"),
                    pipeline=pipeline_value,
                    published=published_value,
                )
            )
    return findings


def _frequency_table(findings: list[Finding]) -> str:
    counter = Counter((f.construct, f.family) for f in findings)
    lines = [
        "| Construct | Family | Articles affected |",
        "| --- | --- | --- |",
    ]
    for (construct, family), count in counter.most_common():
        lines.append(f"| `{construct}` | {family} | {count} |")
    return "\n".join(lines)


def _family_table(findings: list[Finding]) -> str:
    counter = Counter(f.family for f in findings)
    lines = ["| Family | Differences |", "| --- | --- |"]
    for family, count in counter.most_common():
        lines.append(f"| {family} | {count} |")
    return "\n".join(lines)


def _pattern_section(patterns_by_article: dict[str, list]) -> list[str]:
    """Named defect patterns, ranked by how many articles show each."""
    counter = Counter(
        pattern.key for patterns in patterns_by_article.values() for pattern in patterns
    )
    if not counter:
        return ["_No named defect patterns detected._", ""]

    examples = {}
    for patterns in patterns_by_article.values():
        for pattern in patterns:
            examples.setdefault(pattern.key, pattern)

    lines = [
        "These are the actionable defects. Unlike raw count deltas, each is promoted",
        "only when its specific evidence is present.",
        "",
        "| Pattern | Requirement | Articles | What it is |",
        "| --- | --- | ---: | --- |",
    ]
    for key, count in counter.most_common():
        pattern = examples[key]
        lines.append(
            f"| **{pattern.title}** | {pattern.requirement} | {count} | `{key}` |"
        )
    lines.append("")

    for key, count in counter.most_common():
        pattern = examples[key]
        affected = sorted(
            article
            for article, patterns in patterns_by_article.items()
            if any(p.key == key for p in patterns)
        )
        lines.extend(
            [
                f"### {pattern.title}",
                "",
                f"**Requirement:** {pattern.requirement}  ",
                f"**Articles affected:** {count}",
                "",
                pattern.detail,
                "",
                "Affected articles:",
                "",
            ]
        )
        lines.extend(f"- `{article}`" for article in affected)
        lines.append("")

    return lines


def render(
    findings: list[Finding],
    articles_compared: list[str],
    skipped: dict[str, str],
    generated: str,
    patterns_by_article: dict[str, list] | None = None,
    regenerated: list[str] | None = None,
) -> str:
    """Render the full FINDINGS.md document."""
    patterns_by_article = patterns_by_article or {}
    regenerated = regenerated or []
    sections = [
        "# Substack Conversion Findings",
        "",
        "<!-- Generated file. Re-create with: python -m tools.substack_diff --all -->",
        "",
        "Generated by `tools/substack_diff`. Each row is a measured difference between",
        "the pipeline's `article.html` and the corresponding published Substack post.",
        "",
        f"**Generated:** {generated}  ",
        f"**Articles compared:** {len(articles_compared)}  ",
        f"**Total differences:** {len(findings)}",
        "",
        "## How to read this",
        "",
        "A difference means the published post does not match what the pipeline emitted.",
        "Because the author repaired articles by hand in the Substack composer before",
        "publishing, **a difference is a manual fix** — it is the record of work the tool",
        "failed to do.",
        "",
        "`vanished in publication` — the pipeline emitted it, the published post lacks it.  ",
        "`appeared only in publication (hand-added)` — the author added it in the composer.",
        "",
        "> **Caveat 1.** These diffs cannot settle DIAG-01 or FMT-01. Published posts are",
        "> post-repair artifacts, so a clean diff means \"nothing needed fixing *or* the fix",
        "> is invisible at construct-count granularity\" — not \"the pipeline output was",
        "> correct.\" Those requirements need a live paste of current output.",
        "",
        "> **Caveat 2.** Construct counts measure structure, not correctness. Three real",
        "> defects — percent-encoded image paths, stale vault-relative path prefixes, and",
        "> literal inline HTML drawn into rendered tables — produce a *broken image* rather",
        "> than a changed element count, and this diff cannot see any of them. They were",
        "> found by the preflight check and by looking at a rendered PNG.",
        "",
    ]

    if regenerated:
        sections += [
            "> **Caveat 3.** "
            f"{len(regenerated)} article(s) had no archived output and were regenerated "
            "with the *current* code, so their rows reflect today's pipeline rather than "
            "the code that produced the published post. Their defects may already be "
            "fixed. Affected: "
            + ", ".join(f"`{name}`" for name in sorted(regenerated))
            + ".",
            "",
        ]

    sections += [
        "## Confirmed defect patterns",
        "",
    ]
    sections.extend(_pattern_section(patterns_by_article))
    sections += [
        "## Differences by family",
        "",
        "Raw construct-count deltas. Some are editorial changes the author made while",
        "publishing, not tool defects — the pattern section above is the actionable list.",
        "",
        _family_table(findings) if findings else "_No differences detected._",
        "",
        "## Frequency by construct",
        "",
        "Drives fix order — most-affected construct first.",
        "",
        _frequency_table(findings) if findings else "_No differences detected._",
        "",
        "## Per-article detail",
        "",
    ]

    by_article: dict[str, list[Finding]] = {}
    for finding in findings:
        by_article.setdefault(finding.article, []).append(finding)

    for article in articles_compared:
        article_findings = by_article.get(article, [])
        sections.append(f"### {article}")
        sections.append("")
        if not article_findings:
            sections.append("No construct-level differences detected.")
            sections.append("")
            continue
        sections.append("| Construct | Family | Pipeline | Published | Delta | Reading |")
        sections.append("| --- | --- | ---: | ---: | ---: | --- |")
        for finding in sorted(article_findings, key=lambda f: f.construct):
            sections.append(
                f"| `{finding.construct}` | {finding.family} | {finding.pipeline} | "
                f"{finding.published} | {finding.delta:+d} | {finding.headline} |"
            )
        sections.append("")

    if skipped:
        sections.append("## Skipped")
        sections.append("")
        sections.append("| Article | Reason |")
        sections.append("| --- | --- |")
        for article, reason in sorted(skipped.items()):
            sections.append(f"| {article} | {reason} |")
        sections.append("")

    return "\n".join(sections)
