"""CLI for sweeping the fidelity comparator across the vault corpus.

    python -m tools.fidelity_sweep                      # whole corpus, counts
    python -m tools.fidelity_sweep --show               # + the lost text
    python -m tools.fidelity_sweep --article some-slug
    python -m tools.fidelity_sweep --report /tmp/f.md   # counts-only file

Two rules govern what this may write, both from CLAUDE.md:

* **Article prose never enters the repo.** `--report` writes counts only. The
  lost text itself appears on stdout under `--show` and nowhere else, so a
  report file is safe to keep wherever the author puts it.
* **The vault is read-only and unversioned.** Conversion output goes to a
  temporary directory that is deleted on the way out; nothing is written beside
  the source articles.

`docs/FINDINGS.md` is deliberately untouched -- it is generated by
`tools.substack_diff`, and two writers on one file is a collision waiting to
happen.
"""

from __future__ import annotations

import argparse
import logging
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import NamedTuple

from obsidian_to_substack.convert import convert_article
from obsidian_to_substack.fidelity import FidelityReport, compare
from obsidian_to_substack.frontmatter import FRONTMATTER_PATTERN, parse_frontmatter
from obsidian_to_substack.render_html import extract_leading_title
from obsidian_to_substack.table_handler import extract_tables

logger = logging.getLogger("fidelity_sweep")

DEFAULT_VAULT = Path.home() / "Obsidian/BrainBank/4_Archive/Published Articles"


@dataclass(frozen=True)
class ArticleResult:
    """One article's outcome. `error` is set only when conversion itself failed."""

    name: str
    report: FidelityReport | None = None
    error: str | None = None
    error_type: str | None = None

    @property
    def unaccounted_count(self) -> int:
        return len(self.report.unaccounted) if self.report else 0


class Corpus(NamedTuple):
    """What the sweep will measure, and what it left out.

    `skipped` is returned rather than discarded so the census can say how many
    files it declined and why. A corpus that silently narrows is the same
    failure class as the one `260811-dx4` fixed -- a number that under-reports
    without saying so -- and it would be a poor trade to introduce one while
    fixing a denominator.
    """

    articles: list[Path]
    skipped: list[Path]


def has_frontmatter(text: str) -> bool:
    """Did the author write a frontmatter block at the top of this file?

    Deliberately NOT `parse_frontmatter(text)[0]`. That function returns
    `({}, text)` for *both* "no frontmatter" and "frontmatter present but the
    YAML is malformed" -- it collapses the two because for its own purpose the
    outcomes are identical. They are not identical here. An article whose
    header is broken is still an article the author wrote a header for, and
    dropping it from the census would excuse this tool from measuring exactly
    the kind of file it should be measured against.

    So the question is about the delimiter block, not about the parse. The
    pattern is imported rather than re-derived, per the convention that a
    transform and a check making the same judgement share the rule: both are
    asking "is there a frontmatter block here?" and there is one right answer.
    (This is not the `fidelity.py` exception -- that module refuses to share
    because the thing under test is what a transform deleted, so sharing would
    manufacture agreement. Nothing is under test here.)
    """
    return FRONTMATTER_PATTERN.match(text) is not None


def find_articles(vault: Path) -> Corpus:
    """The corpus: every Markdown file whose author wrote a frontmatter block.

    Both layouts are covered: a bare `article.md` and the newer
    directory-with-`svg/` form, whose Markdown still sits at the top level.

    **Why frontmatter and not the file extension.** The 2026-08-10 preflight
    census found that 4 of 12 corpus warnings came from companion LinkedIn
    promo posts -- short, header-less, and sitting *inside* their parent
    article's own directory, which is why no path rule could separate them.
    They were never going to be pasted into Substack, and because this same
    selection defines the fidelity baseline, they were silently inflating its
    denominator.

    **The accepted cost, and it is real.** Three genuine articles have no
    frontmatter (`equipment-qualification-taxonomy`, `productive and
    efficient`, `working with procurement?` -- the census's three true
    `slug_title` warnings) and this rule does not see them. Accepted because it
    is self-correcting: the fix for those three is one `title:` line each in
    the vault, which re-admits them automatically. The part that is NOT
    self-correcting and is worth knowing: while they sit outside, every article
    in the corpus has frontmatter, so **`slug_title` is a check no sweep can
    trip.** Do not read a census with zero `slug_title` findings as good news.

    Unreadable files are kept rather than dropped, for the same fail-closed
    reason `has_frontmatter` includes a malformed header: a file that vanishes
    from the census leaves nothing behind to notice.
    """
    articles: list[Path] = []
    skipped: list[Path] = []

    for path in sorted(p for p in vault.rglob("*.md") if p.is_file()):
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            logger.debug("could not read %s; keeping it in the corpus", path)
            articles.append(path)
            continue

        (articles if has_frontmatter(text) else skipped).append(path)

    return Corpus(articles=articles, skipped=skipped)


def sweep_article(source_path: Path, output_root: Path) -> ArticleResult:
    """Convert one article and compare its output against its source."""
    try:
        result = convert_article(str(source_path), str(output_root))
    except Exception as exc:  # noqa: BLE001 - a sweep must survive one bad article
        logger.debug("conversion failed for %s", source_path, exc_info=True)
        return ArticleResult(
            name=source_path.name,
            error=f"{type(exc).__name__}: {exc}",
            error_type=type(exc).__name__,
        )

    raw_text = source_path.read_text(encoding="utf-8")
    html = Path(result["html_path"]).read_text(encoding="utf-8")

    # Re-derive the same evidence convert_article held, so the comparator can
    # account for the title and the tables. These are reads of the source, not
    # of the transforms under test -- extract_tables is the source of truth for
    # what the table images actually received.
    metadata, body = parse_frontmatter(raw_text)
    authored_title = extract_leading_title(body) or metadata.get("title", "")
    resolved_title = authored_title or source_path.stem.replace("-", " ")
    tables = [rows for _start, _end, _raw, rows in extract_tables(body)]

    report = compare(
        raw_text,
        html,
        resolved_title=resolved_title,
        tables=tables,
    )
    return ArticleResult(name=source_path.name, report=report)


def summarize(results: list[ArticleResult], skipped_count: int = 0) -> str:
    """A counts-only census. Safe to write to a file — carries no article prose."""
    converted = [r for r in results if r.error is None]
    failed = [r for r in results if r.error is not None]
    dirty = [r for r in converted if r.unaccounted_count]
    total_findings = sum(r.unaccounted_count for r in converted)

    source_words = sum(r.report.source_word_count for r in converted if r.report)
    compared_words = sum(r.report.compared_word_count for r in converted if r.report)
    coverage = (compared_words / source_words) if source_words else 1.0

    lines = [
        "# Fidelity sweep",
        "",
        f"- Articles found: {len(results)}",
        # Stated even when zero. The corpus is now a filtered set, and a census
        # that shrank without saying so would read as articles having vanished
        # -- which is the exact misreading this line exists to prevent.
        f"- Skipped (no frontmatter, not articles): {skipped_count}",
        f"- Converted: {len(converted)}",
        f"- Conversion failures: {len(failed)}",
        f"- Clean: {len(converted) - len(dirty)}",
        f"- With unaccounted removals: {len(dirty)}",
        f"- Total unaccounted removals: {total_findings}",
        # A clean sweep is only meaningful next to this: every authorized span
        # withholds words, so a check that authorized everything would also
        # read clean. Coverage separates "nothing was lost" from "nothing was
        # looked at", and belongs beside the finding count wherever it is
        # quoted.
        f"- Words compared: {compared_words:,} of {source_words:,} ({coverage:.1%})",
        "",
    ]

    if dirty:
        lines.append("## Articles with unaccounted removals")
        lines.append("")
        lines.append("| Article | Removals | Source words |")
        lines.append("|---------|----------|--------------|")
        for result in sorted(dirty, key=lambda r: -r.unaccounted_count):
            words = result.report.source_word_count if result.report else 0
            lines.append(f"| {result.name} | {result.unaccounted_count} | {words} |")
        lines.append("")

    if failed:
        lines.append("## Conversion failures")
        lines.append("")
        # Exception TYPE only, never the message. `result.error` carries
        # `str(exc)`, and a UnicodeDecodeError or a parse error embeds a
        # fragment of the article's own text in it -- which would put article
        # prose into a file this module promises carries none. The full
        # message stays on stdout, where the rest of the prose already is.
        for result in failed:
            lines.append(f"- {result.name} — {result.error_type}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sweep the fidelity comparator across the vault corpus."
    )
    parser.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    parser.add_argument("--article", help="Only sweep articles whose name contains this")
    parser.add_argument(
        "--show",
        action="store_true",
        help="Print the lost text (stdout only — never written to a file)",
    )
    parser.add_argument(
        "--report",
        type=Path,
        help="Write the counts-only census here (carries no article prose)",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.WARNING,
        format="%(levelname)s %(message)s",
    )

    if not args.vault.is_dir():
        print(f"Vault not found: {args.vault}", file=sys.stderr)
        raise SystemExit(2)

    corpus = find_articles(args.vault)
    articles = corpus.articles
    if args.article:
        needle = args.article.casefold()
        articles = [p for p in articles if needle in p.name.casefold()]

    if not articles:
        print("No articles matched.", file=sys.stderr)
        raise SystemExit(1)

    # Named up front, before any result scrolls past. A reader who sees only
    # the trailing census should not have to work out why the article count
    # changed, and a file skipped in error is only findable if it is announced.
    if corpus.skipped:
        print(f"Skipped {len(corpus.skipped)} file(s) with no frontmatter — not articles:")
        for path in corpus.skipped:
            print(f"   -  {path.name}")
        print()

    results: list[ArticleResult] = []
    # A temporary output root, removed on the way out: the sweep converts real
    # vault articles, and their rendered text must not be left on disk inside
    # the repo where output/ would carry it.
    with tempfile.TemporaryDirectory(prefix="fidelity-sweep-") as tmp:
        for source_path in articles:
            result = sweep_article(source_path, Path(tmp))
            results.append(result)

            if result.error:
                print(f"!  {result.name}: {result.error}")
            elif result.unaccounted_count:
                print(f"×  {result.name}: {result.unaccounted_count} unaccounted")
                if args.show and result.report:
                    for removal in result.report.unaccounted:
                        print(removal.format())
            else:
                print(f"·  {result.name}")

    census = summarize(results, skipped_count=len(corpus.skipped))
    print()
    print(census)

    if args.report:
        args.report.write_text(census, encoding="utf-8")
        print(f"Census written to {args.report}")


if __name__ == "__main__":
    main()
