"""CLI for sweeping the fidelity comparator across the vault corpus.

    python -m tools.fidelity_sweep                      # whole corpus, counts
    python -m tools.fidelity_sweep --show               # + the lost text
    python -m tools.fidelity_sweep --article some-slug
    python -m tools.fidelity_sweep --report /tmp/f.md   # counts-only file

Two rules govern what this may write, both from CLAUDE.md:

* **Article prose never enters the repo.** `--report` writes counts only. The
  lost text itself appears on stdout under `--show` and nowhere else, so a
  report file is safe to keep wherever the author puts it.
* **The vault is read-only and unversioned.** Conversion output goes to a
  temporary directory that is deleted on the way out; nothing is written beside
  the source articles.

`docs/FINDINGS.md` is deliberately untouched -- it is generated by
`tools.substack_diff`, and two writers on one file is a collision waiting to
happen.
"""

from __future__ import annotations

import argparse
import logging
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from obsidian_to_substack.convert import convert_article
from obsidian_to_substack.fidelity import FidelityReport, compare
from obsidian_to_substack.frontmatter import parse_frontmatter
from obsidian_to_substack.render_html import extract_leading_title
from obsidian_to_substack.table_handler import extract_tables

logger = logging.getLogger("fidelity_sweep")

DEFAULT_VAULT = Path.home() / "Obsidian/BrainBank/4_Archive/Published Articles"


@dataclass(frozen=True)
class ArticleResult:
    """One article's outcome. `error` is set only when conversion itself failed."""

    name: str
    report: FidelityReport | None = None
    error: str | None = None
    error_type: str | None = None

    @property
    def unaccounted_count(self) -> int:
        return len(self.report.unaccounted) if self.report else 0


def find_articles(vault: Path) -> list[Path]:
    """Every Markdown article in the corpus, in a stable order.

    Both corpus layouts are covered: a bare `article.md` and the newer
    directory-with-`svg/` form, whose Markdown still sits at the top level.
    """
    return sorted(p for p in vault.rglob("*.md") if p.is_file())


def sweep_article(source_path: Path, output_root: Path) -> ArticleResult:
    """Convert one article and compare its output against its source."""
    try:
        result = convert_article(str(source_path), str(output_root))
    except Exception as exc:  # noqa: BLE001 - a sweep must survive one bad article
        logger.debug("conversion failed for %s", source_path, exc_info=True)
        return ArticleResult(
            name=source_path.name,
            error=f"{type(exc).__name__}: {exc}",
            error_type=type(exc).__name__,
        )

    raw_text = source_path.read_text(encoding="utf-8")
    html = Path(result["html_path"]).read_text(encoding="utf-8")

    # Re-derive the same evidence convert_article held, so the comparator can
    # account for the title and the tables. These are reads of the source, not
    # of the transforms under test -- extract_tables is the source of truth for
    # what the table images actually received.
    metadata, body = parse_frontmatter(raw_text)
    authored_title = extract_leading_title(body) or metadata.get("title", "")
    resolved_title = authored_title or source_path.stem.replace("-", " ")
    tables = [rows for _start, _end, _raw, rows in extract_tables(body)]

    report = compare(
        raw_text,
        html,
        resolved_title=resolved_title,
        tables=tables,
    )
    return ArticleResult(name=source_path.name, report=report)


def summarize(results: list[ArticleResult]) -> str:
    """A counts-only census. Safe to write to a file — carries no article prose."""
    converted = [r for r in results if r.error is None]
    failed = [r for r in results if r.error is not None]
    dirty = [r for r in converted if r.unaccounted_count]
    total_findings = sum(r.unaccounted_count for r in converted)

    source_words = sum(r.report.source_word_count for r in converted if r.report)
    compared_words = sum(r.report.compared_word_count for r in converted if r.report)
    coverage = (compared_words / source_words) if source_words else 1.0

    lines = [
        "# Fidelity sweep",
        "",
        f"- Articles found: {len(results)}",
        f"- Converted: {len(converted)}",
        f"- Conversion failures: {len(failed)}",
        f"- Clean: {len(converted) - len(dirty)}",
        f"- With unaccounted removals: {len(dirty)}",
        f"- Total unaccounted removals: {total_findings}",
        # A clean sweep is only meaningful next to this: every authorized span
        # withholds words, so a check that authorized everything would also
        # read clean. Coverage separates "nothing was lost" from "nothing was
        # looked at", and belongs beside the finding count wherever it is
        # quoted.
        f"- Words compared: {compared_words:,} of {source_words:,} ({coverage:.1%})",
        "",
    ]

    if dirty:
        lines.append("## Articles with unaccounted removals")
        lines.append("")
        lines.append("| Article | Removals | Source words |")
        lines.append("|---------|----------|--------------|")
        for result in sorted(dirty, key=lambda r: -r.unaccounted_count):
            words = result.report.source_word_count if result.report else 0
            lines.append(f"| {result.name} | {result.unaccounted_count} | {words} |")
        lines.append("")

    if failed:
        lines.append("## Conversion failures")
        lines.append("")
        # Exception TYPE only, never the message. `result.error` carries
        # `str(exc)`, and a UnicodeDecodeError or a parse error embeds a
        # fragment of the article's own text in it -- which would put article
        # prose into a file this module promises carries none. The full
        # message stays on stdout, where the rest of the prose already is.
        for result in failed:
            lines.append(f"- {result.name} — {result.error_type}")
        lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Sweep the fidelity comparator across the vault corpus."
    )
    parser.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    parser.add_argument("--article", help="Only sweep articles whose name contains this")
    parser.add_argument(
        "--show",
        action="store_true",
        help="Print the lost text (stdout only — never written to a file)",
    )
    parser.add_argument(
        "--report",
        type=Path,
        help="Write the counts-only census here (carries no article prose)",
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.WARNING,
        format="%(levelname)s %(message)s",
    )

    if not args.vault.is_dir():
        print(f"Vault not found: {args.vault}", file=sys.stderr)
        raise SystemExit(2)

    articles = find_articles(args.vault)
    if args.article:
        needle = args.article.casefold()
        articles = [p for p in articles if needle in p.name.casefold()]

    if not articles:
        print("No articles matched.", file=sys.stderr)
        raise SystemExit(1)

    results: list[ArticleResult] = []
    # A temporary output root, removed on the way out: the sweep converts real
    # vault articles, and their rendered text must not be left on disk inside
    # the repo where output/ would carry it.
    with tempfile.TemporaryDirectory(prefix="fidelity-sweep-") as tmp:
        for source_path in articles:
            result = sweep_article(source_path, Path(tmp))
            results.append(result)

            if result.error:
                print(f"!  {result.name}: {result.error}")
            elif result.unaccounted_count:
                print(f"×  {result.name}: {result.unaccounted_count} unaccounted")
                if args.show and result.report:
                    for removal in result.report.unaccounted:
                        print(removal.format())
            else:
                print(f"·  {result.name}")

    census = summarize(results)
    print()
    print(census)

    if args.report:
        args.report.write_text(census, encoding="utf-8")
        print(f"Census written to {args.report}")


if __name__ == "__main__":
    main()
